import theme from "./theme";

export const useStyles = () => ({
    root: {
      position: 'relative',
      minHeight: '100vh',
      overflowX: 'hidden',
      backgroundImage: 'url(/se5.jpeg)',
      backgroundSize: 'contain',
      backgroundPosition: 'center',
      backgroundRepeat: 'no-repeat',
      backgroundAttachment: 'fixed',
      backgroundColor: 'black',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
    },
    container: {
      position: 'relative',
      backgroundColor: 'rgba(0, 0, 0, 0.3)',
      borderRadius: '24px',
      padding: '24px',
      marginTop: '100px',
      [theme.breakpoints.down('md')]: {
        marginTop: '130px'
      },
    },
    title: {
      fontWeight: 700,
      color: 'white',
      textAlign: 'center',
      [theme.breakpoints.down('md')]: {
        marginTop: theme.spacing(3),
      },
    },
    introduction: {
      mt: 5,
      mb: 10,
      textAlign: 'center',
      color: 'black',
    },
    introductionText: {
      color: '#d3d3d3',
      fontWeight: 400,
    },
    section: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      mb: 6,
    },
    sectionTitle: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      color: '#d3d3d3',
      textAlign: 'center',
      fontWeight: 500,
    },
    gridContainer: {
      mt: 2,
    },
    line: {
      position: 'absolute',
      width: '1px',
      height: '80%',
      backgroundColor: '#d3d3d3',
      left: '10px',
      top: '40px',
    },
    paper: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      position: 'relative',
      marginBottom: '100px',
      marginLeft: '50px',
      marginRight: '50px',
      [theme.breakpoints.down('md')]: {
        marginLeft: '5px',
        marginRight: '5px',
      },
    },
    points: {
      position: 'absolute',
      left: '-44px',
      top: 0,
      width: '8px',
      height: '8px',
      borderRadius: '50%',
      backgroundColor: '#d3d3d3',
      border: '2px solid #d3d3d3',
      [theme.breakpoints.down('md')]: {
        marginLeft: '45px',
        marginRight: '45px',
      },
    },
    paperTitle: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      color: '#d3d3d3',
      textAlign: 'center',
      fontWeight: 600,
    },
    paperText: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      textAlign: 'justify',
      color: '#d3d3d3',
      mt: 1,
      [theme.breakpoints.down('md')]: {
        textAlign: 'left',
      },
    },
    personalJourneyText: {
      mt: 3,
      color: '#d3d3d3',
      maxWidth: '800px',
      textAlign: 'justify',
    },
    callToAction: {
      marginTop: 5,
      marginBottom: 15,
      justifyContent: 'center',
    },
    button: {
        color: 'white',
        border: '0.1px solid rgba(255, 255, 255, 0.1)',
        borderRadius: '15px',
        padding: theme.spacing(1, 2),
        fontWeight: '500',
        fontSize: '14px',
        textTransform: 'capitalize',
        '&:hover': {
          backgroundColor: 'rgba(255, 255, 255, 0.2)',
          borderColor: 'white',
        },
        [theme.breakpoints.down('md')]: {
            fontSize: 12,
        },
    },
    footer: {
      position: 'fixed',
      bottom: 0,
      left: 0,
      width: '100%',
      backgroundColor: 'rgba(0, 0, 0, 0.7)',
      padding: '10px',
      textAlign: 'left',
      color: '#d3d3d3',
      fontSize: '14px',
      zIndex: 10,
    },
  });
  