import theme from './theme';

export const styles = {
  root: {
    position: 'relative',
    minHeight: '100vh',
    overflowX: 'hidden',
    backgroundImage: 'url(/se5.jpeg)',
    backgroundSize: 'contain',
    backgroundPosition: 'center',
    backgroundRepeat: 'no-repeat',
    backgroundAttachment: 'fixed',
    backgroundColor: 'black',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  container: {
    textAlign: 'center',
    marginTop: 10,
    [theme.breakpoints.down('md')]: {
      marginTop: 20,
    },
  },
  title: {
    marginBottom: theme.spacing(4),
    fontWeight: 'bold',
    color: '#d3d3d3',
    [theme.breakpoints.down('md')]: {
      fontSize: 28,
      marginTop: theme.spacing(3),
    },
  },
  caption: {
    fontSize: '10px',
    color: 'black',
    paddingTop: '5px',
    display: "block",
    flexDirection: 'column',
    margin: '0 auto',
    textAlign: 'center',
  },
  image: {
    width: '100%',
    maxWidth: '250px',
    height: 'auto',
    marginBottom: { xs: theme.spacing(2), md: 0 },
    marginRight: { md: theme.spacing(2) },
  },
  image2: {
    display: "block",
    flexDirection: 'column',
    width: '100%',
    maxWidth: '400px',
    margin: '0 auto',
    height: 'auto',
  },
  image3: {
    display: "block",
    flexDirection: 'column',
    width: '100%',
    maxWidth: '400px',
    margin: '0 auto',
    height: 'auto',
  },
  contentPaper: {
    padding: theme.spacing(3),
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
    borderRadius: '8px',
    boxShadow: '0 4px 8px rgba(0, 0, 0, 0.2)',
    marginBottom: theme.spacing(3),
    display: 'flex',
    flexDirection: { xs: 'column', md: 'row' },
    alignItems: 'flex-start',
  },
  text: {
    color: '#333',
    textAlign: 'justify',
    lineHeight: 1.6,
  },
  backLink: {
    color: '#d3d3d3',
    fontSize: '16px',
    textDecoration: 'underline',
    '&:hover': {
      color: 'white',
    },
  },
  callToAction: {
    marginTop: 5,
    marginBottom: 15,
    justifyContent: 'center',
  },
  button: {
    color: 'white',
    border: '0.1px solid rgba(255, 255, 255, 0.1)',
    borderRadius: '15px',
    padding: theme.spacing(1, 2),
    fontWeight: '500',
    fontSize: '14px',
    textTransform: 'capitalize',
    '&:hover': {
      backgroundColor: 'rgba(255, 255, 255, 0.2)',
      borderColor: 'white',
    },
    [theme.breakpoints.down('md')]: {
      fontSize: 12,
    },
  },
  footer: {
    position: 'fixed',
    bottom: 0,
    left: 0,
    width: '100%',
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    padding: '10px',
    textAlign: 'left',
    color: '#d3d3d3',
    fontSize: '14px',
    zIndex: 10,
},
};
